version: "3.4"

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos